
name: Building
run-name: Building without testing
on:
  push:
    branches:
      - main
jobs:
  Premier-Job:
    runs-on:  ubuntu-latest
    steps:
      - uses: Leila1927 /GitActions-Testing/.gitflow/workflow/reuse.yml 
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
