
name: Building
run-name: Building 
on:
  push:
    branches:
      - main
jobs:
  Set-up:
    uses: Leila1927/GitActions-Testing/.github/workflows/reuse.yml@main
  Build:
    runs-on:  ubuntu-latest
    steps:
      - uses: Actions/checkout@v3
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
