
name: Building
run-name: Building 
on:
  push:
    branches:
      - main
jobs:
  Premier-Job:
    uses: Leila1927/GitActions-Testing/.github/workflows/reuse.yml@main
    runs-on:  ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
