
name: Quality check with sonar
run-name: Quality Check
on:
  workflow_run:
    workflows: ['test-ter']
    types:
      - completed
jobs:
  Set-up:
    uses: Leila1927/GitActions-Testing/.github/workflows/reuse.yml@main
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions/checkout@v3
      - name: Analyze with SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Leila1927_GitActions-Testing 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}