
name: Quality check with sonar
run-name: Quality Check
on:
  push:
    branches:
      - main
jobs:
  Set-up:
    uses: Leila1927/GitActions-Testing/.github/workflows/reuse.yml@main
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions/checkout@v2
      - name: Analyze with SonarCloud
        run:  mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Leila1927_GitActions-Testing -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}