
name: Reuse setup
run-name: Reusable Setup
on:
  workflow_call:
jobs:
  Setup-enviroment:
    runs-on:  ubuntu-latest
    steps:
      - name: Set up JDK 11 
        uses: Actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'adopt'