name: Ter-test
run-name: Testing
on:
  push:
    branches:
      - main
jobs:
  Test:
    runs-on:  ubuntu-latest
    steps:
      - uses: Actions/checkout@v3
      - name: Tes
        run: echo 'hey'
      - uses: Leila1927/GitActions-Testing/.gitflow/workflows/reuse.yml@main
      - name: Testing with maven
        run: mvn test
      - name: Archive jacoco coverage results
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: target/