name: Ter-test
run-name: Testing
on:
  push:
    branches:
      - main
jobs:
  Test:
    runs-on:  ubuntu-latest
    uses: Leila1927/GitActions-Testing/.github/workflows/reuse.yml@main
    steps:
      - name: Testing with maven
        run: mvn test
      - name: Archive jacoco coverage results
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: target/